### PR TITLE
Portuguese Translation

### PR DESCRIPTION
**Pull request by gabriel-del**
I add a portuguese translation to your site.
I also changed a few english files which wasn't translated.

### CODE REVIEW

**Comment by LeeU1911** [comment]
Hey Gabriel, It's so cool that you helped spent effort for translating content into Portuguese. On behalf of DalaFarm team, we really appreciate it! Thanks a lot!

**Comment by LeeU1911** [comment]
@gabriel-del Btw, we have a plan to port this into a separated open-source hugo e-commerce theme which was lacking at the time we created. Are you interested in doing that?

**Comment by gabriel-del** [comment]
Yes, sure. How can I help you?

Thank you for accept my commits :)

**Comment by LeeU1911** [comment]
Ok cool. So we'll start off with clone this repo into a separated independent one. Then removing specific content belong to DalaFarm and only leave the general content. Then we'll start to refactor the code and publish it to Hugo theme repo.

I'll do the first step tonight and share the repo with you.

**Comment by LeeU1911** [comment]
@gabriel-del I created https://github.com/LeeU1911/hugo-ecommerce-theme which is a barebone from this repo. Starting from now, we can add stuff to make that theme working with only necessary stuffs.

**Comment by gabriel-del** [comment]
Nice! you can use:
git submodule add git@github.com:LeeU1911/hugo-ecommerce-theme.git themes/hugo-ecommerce-theme

on you dalafarm folder to sync it automatically.
I will take a look.

**Pull request merged**
